name: .NET continuous build and test

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'test/**'
      - 'examples/**'
      - '*.sln'
      - '.github/workflows/*'

jobs:
  continuous_build_test_pack_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack
        run: |
          dotnet pack src/Fenris.OneOfContrib.Blazor/ \
            -c Release \
            -o ./artifacts \
            --verbosity minimal \
            -p:PackageVersion=1.0.4-${{ github.run_number }}-alpha
      - name: Push to nuget.org
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key ${{ secrets.NUGET_TOKEN }}
      - name: Push symbols to nuget.org
        run: |
          dotnet nuget push ./artifacts/*.snupkg \
            --source "https://www.nuget.org/api/v2/symbolpackage" \
            --api-key ${{ secrets.NUGET_TOKEN }}
