name: .NET continuous build and test

on:
  push:
    branches:
      - '*'
    paths:
      - 'src/**'
      - 'test/**'
      - 'examples/**'
      - '*.sln'

jobs:
  continuous_build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack Fenris.OneOfContrib.Blazor
        run: dotnet pack src/Fenris.OneOfContrib.Blazor/ -c Release -o ./artifacts --include-source --verbosity minimal -p:PackageVersion=0.1.${{ github.run_number }}-alpha
      - name: Push to nuget.org
        run: dotnet nuget push ./artifacts/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_TOKEN }} 
